---
title: "Compras Estatales"
author: "Daniel Czarnievicz"
date: "Última actualización: `r format(Sys.time(), '%A %d %B, %Y, %I:%M %p')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    toc_float: 
      smooth_scroll: true
    theme: united
    highlight: tango
    fig_caption: true
    code_folding: hide
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::knit_hooks$set(inline = function(x) {prettyNum(x, big.mark = ".")})
library(knitr)
library(tidyverse)
library(lubridate)
library(formattable)
library(kableExtra)
library(magrittr)
```

```{r}
compras <- readr::read_rds("Csv/compras.rds")
adjudicaciones <- readr::read_rds("Csv/adjudicaciones.rds")
oferentes <- readr::read_rds("Csv/oferentes.rds")
```

# Análisis oferentes {.tabset .tabset-fade .tabset-pills}

```{r}
# Cantidad de oferentes
cant_provs_oferentes <- oferentes %>% 
  count(nro_doc_prov) %>% 
  dim() %>% 
  .[1]
# Cantidad de compras
cant_compras <- compras %>% 
  count(id_compra) %>% 
  dim() %>% 
  .[1]
```

La base cuenta con información sobre `r cant_provs_oferentes` proveedores, los cuales han partidicado de un total de `r cant_compras` compras. El proveedor más frecuente durante 2018 fue Nalfer SA, quien participó en el 4,10% de las compras.

```{r}
# Principales oferentes del estado
oferentes %>% 
  group_by(nro_doc_prov, nombre_comercial) %>% 
  summarise(n_compras = n_distinct(id_compra)) %>% 
  ungroup() %>%
  mutate(prop = percent(n_compras / sum(n_compras), digits = 2)) %>%
  arrange(desc(n_compras, nombre_comercial)) %>%
  select(nombre_comercial, nro_doc_prov, n_compras, prop) %>% 
  head(10) %>%
  kable(format = "html", format.args = list(big.mark = ".", decimal.mark = ","), escape = FALSE,
        caption = "Principales oferentes del Estado en 2018 y 2019",
        col.names = c("Proveedor", "ID", "Cantidad", "Proporción")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)
```

# Análisis compras

```{r, fig.align='center', fig.cap="Evolución del monto total adjudicado por mes\n(en millones de pesos corrientes)"}
# Falta tasas de cambio
compras %>% 
  filter("2018-01-01" < fecha_compra, fecha_compra < "2018-12-31", monto_adj > 0) %>%
  group_by(floor_date(fecha_compra, "week")) %>% 
  summarise(total_comprado = sum(monto_adj_pesos, na.rm = TRUE)) %>% 
  ggplot() +
  geom_line(aes(`floor_date(fecha_compra, "week")`, total_comprado), color = "purple") +
  labs(x = NULL, y = "Monto total adjudicado por semana\n(equivalente en millones de pesos corrientes)\n") +
  scale_y_continuous(labels = scales::dollar_format(prefix = "$U", big.mark = ".", decimal.mark = ",", scale = 1/1e6)) +
  ggthemes::theme_economist() +
  theme(axis.title = element_text(face = "bold"))
```

```{r, fig.align='center', fig.cap="Evolución de la cantidad de adjudicaciones mensuales"}
compras %>% 
  filter("2018-01-01" < fecha_compra, fecha_compra < "2018-12-30", monto_adj > 0) %>%
  group_by(floor_date(fecha_compra, "week")) %>% 
  tally() %>% 
  ggplot() +
  geom_line(aes(`floor_date(fecha_compra, "week")`, n), color = "orange") +
  labs(x = NULL, y = "Cantidad de adjudicaciones mensuales\n") +
  scale_y_continuous(labels = scales::number_format(big.mark = ".", decimal.mark = ",")) +
  ggthemes::theme_economist() +
  theme(axis.title = element_text(face = "bold"))
```

```{r, fig.align='center', fig.cap="Monto total adjudicado por semana en función de la cantidad de adjudicaciones realizadas."}
#Hice esta visualización porque me llama la atención que en las dos gráficas anteriores, antes de abril de 2018 se da el maximo del monto adjudicado pero el minimo de cantidad de adjudicaciones. Para poder analizar eso bien hacen falta las tasas de cambio (sino de la grafica de mondo adjudicado por semana no se puede sacar ninguna información. También habría que ver si vamos a sacar las compras que no se realizaron de la base.

compras %>% 
  filter("2018-01-01" < fecha_compra, fecha_compra < "2018-12-31", monto_adj > 0) %>%
  group_by(floor_date(fecha_compra, "week"), monto_adj_pesos) %>% tally() %>% 
  summarise(cant_adjs=sum(n), total_comprado = sum(monto_adj_pesos,
    na.rm = TRUE) ) %>%
  ggplot() + geom_line(aes(x=cant_adjs, y=total_comprado)) +
  labs(x = "Cantidad de adjudicaciones mensuales\n", y = "Monto total adjudicado por semana\n(equivalente en millones de pesos corrientes)\n") +
  scale_y_continuous(labels = scales::dollar_format(prefix = "$U", big.mark = ".", decimal.mark = ",", scale = 1/1e6)) +
  ggthemes::theme_economist() +
  theme(axis.title = element_text(face = "bold"))
  
```


```{r fig.align='center', fig.cap="Asociación entre el tiempo que requiró concluir la compra (span) y el monto involucrado en la compra según moneda de la compra. No parecería existir una relación entre las mismas."}
compras %>% 
  mutate(span = (fecha_compra %--% fecha_pub_adj) %/% hours(1),
         pesos = if_else(id_moneda == 0, "Compra en pesos", "Compra en otra moneda")) %>% 
  ggplot() +
  geom_point(aes(log(span), log(monto_adj_pesos), color = pesos), alpha = 1/5) +
  labs(x = "\nSpan de la compra (en logs - en días)", 
       y = "Monto de la compra\n(en logs - en pesos corrientes)\n", 
       color = NULL) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  # scale_x_continuous(labels = scales::number_format(scale = 1/24)) +
  ggthemes::theme_economist() +
  theme(axis.title = element_text(face = "bold"),
        legend.position = "bottom")
```

```{r fig.align='center', fig.cap="Distribución del logaritmo del tiempo que requiró concluir la compra (span) según  la misma tuvo o no apertura electrónica."}
compras %>% 
  filter(!is.na(apel)) %>% 
  mutate(span = (fecha_compra %--% fecha_pub_adj) %/% hours(1),
         pesos = if_else(id_moneda == 0, "Compra en pesos", "Compra en otra moneda"),
         apel = if_else(apel == "Yes", "Sí", "No")) %>% 
  ggplot() +
  geom_histogram(aes(x = log(span), y = ..density.., fill = apel)) +
  facet_wrap(~apel) +
  labs(x = "Span de la compra (en logs - en días)", y = "Proporción", fill = "Apertura\nElectrónica") +
  # guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  # scale_x_continuous(labels = scales::number_format(scale = 1/24)) +
  ggthemes::theme_economist() +
  theme(axis.title = element_text(face = "bold"),
        legend.position = "bottom",
        strip.text = element_blank())
```

